"""word_translations

Revision ID: 33b02a5a863d
Revises: b4d0da2aef70
Create Date: 2026-09-30 13:03:55.688663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33b02a5a863d"
down_revision: str | Sequence[str] | None = "b4d0da2aef70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_translations",
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), server_default="mymemory", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("word", name=op.f("pk_word_translations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_translations")
    # ### end Alembic commands ###
