"""books and article chapters

Revision ID: a1881360bff3
Revises: 33b02a5a863d
Create Date: 2026-09-30 14:07:48.152364

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1881360bff3"
down_revision: str | Sequence[str] | None = "33b02a5a863d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("page_count >= 0", name=op.f("ck_books_page_count_non_negative")),
        sa.CheckConstraint("word_count >= 0", name=op.f("ck_books_word_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_books_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
    )
    op.add_column("articles", sa.Column("book_id", sa.BigInteger(), nullable=True))
    op.add_column("articles", sa.Column("position", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_articles_book_id"), "articles", ["book_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_articles_book_id_books"),
        "articles",
        "books",
        ["book_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_articles_book_id_books"), "articles", type_="foreignkey")
    op.drop_index(op.f("ix_articles_book_id"), table_name="articles")
    op.drop_column("articles", "position")
    op.drop_column("articles", "book_id")
    op.drop_table("books")
    # ### end Alembic commands ###
