"""daily_stats goal_met

Revision ID: b4d0da2aef70
Revises: bd45b62e8151
Create Date: 2026-09-30 11:53:02.994790

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4d0da2aef70"
down_revision: str | Sequence[str] | None = "bd45b62e8151"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_stats",
        sa.Column("goal_met", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_stats", "goal_met")
    # ### end Alembic commands ###
