"""initial schema

Revision ID: bd45b62e8151
Revises:
Create Date: 2026-09-26 17:40:12.775769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd45b62e8151"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty IN ('A1','A2','B1','B2','C1')", name=op.f("ck_articles_difficulty")
        ),
        sa.CheckConstraint("word_count >= 0", name=op.f("ck_articles_word_count_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("source_url", name=op.f("uq_articles_source_url")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("english_level", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "english_level IN ('A1','A2','B1','B2','C1')", name=op.f("ck_users_english_level")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "daily_stats",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("words_read", sa.Integer(), server_default="0", nullable=False),
        sa.Column("seconds_read", sa.Integer(), server_default="0", nullable=False),
        sa.Column("xp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("texts_completed", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "seconds_read >= 0", name=op.f("ck_daily_stats_seconds_read_non_negative")
        ),
        sa.CheckConstraint(
            "texts_completed >= 0", name=op.f("ck_daily_stats_texts_completed_non_negative")
        ),
        sa.CheckConstraint("words_read >= 0", name=op.f("ck_daily_stats_words_read_non_negative")),
        sa.CheckConstraint("xp >= 0", name=op.f("ck_daily_stats_xp_non_negative")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_daily_stats_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "day", name=op.f("pk_daily_stats")),
    )
    op.create_table(
        "reading_goals",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("goal_type", sa.Text(), server_default="words", nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("goal_type IN ('words')", name=op.f("ck_reading_goals_goal_type")),
        sa.CheckConstraint("target > 0", name=op.f("ck_reading_goals_target_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reading_goals_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_goals")),
    )
    op.create_index(
        "uq_reading_goals_user_id_active",
        "reading_goals",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "reading_progress",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("words_read", sa.Integer(), server_default="0", nullable=False),
        sa.Column("seconds_read", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress BETWEEN 0 AND 100", name=op.f("ck_reading_progress_progress_range")
        ),
        sa.CheckConstraint(
            "seconds_read >= 0", name=op.f("ck_reading_progress_seconds_read_non_negative")
        ),
        sa.CheckConstraint(
            "words_read >= 0", name=op.f("ck_reading_progress_words_read_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_reading_progress_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reading_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_progress")),
        sa.UniqueConstraint(
            "user_id", "article_id", name=op.f("uq_reading_progress_user_id_article_id")
        ),
    )
    op.create_table(
        "saved_words",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_saved_words_article_id_articles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_words_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_words")),
        sa.UniqueConstraint("user_id", "word", name=op.f("uq_saved_words_user_id_word")),
    )
    op.create_table(
        "streaks",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("current", sa.Integer(), server_default="0", nullable=False),
        sa.Column("longest", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_active_day", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_streaks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_streaks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("streaks")
    op.drop_table("saved_words")
    op.drop_table("reading_progress")
    op.drop_index(
        "uq_reading_goals_user_id_active",
        table_name="reading_goals",
        postgresql_where=sa.text("active"),
    )
    op.drop_table("reading_goals")
    op.drop_table("daily_stats")
    op.drop_table("users")
    op.drop_table("articles")
    # ### end Alembic commands ###
