"""users last_reading_at

Revision ID: fde7c6049469
Revises: a1881360bff3
Create Date: 2026-09-30 14:55:43.956817

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fde7c6049469"
down_revision: str | Sequence[str] | None = "a1881360bff3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_reading_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_reading_at")
    # ### end Alembic commands ###
